// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package serve

import (
	"github.com/google/wire"
	"github.com/wenzong/demo/biz/user"
	"github.com/wenzong/demo/infra/app"
	"github.com/wenzong/demo/infra/config"
	"github.com/wenzong/demo/infra/db"
	"github.com/wenzong/demo/infra/grpc"
	"github.com/wenzong/demo/infra/http"
)

// Injectors from wire.go:

func App() *app.App {
	viper := config.NewConfig()
	option := http.NewOption(viper)
	defaultConn := db.NewDefaultConn(viper)
	repository := user.NewRepository(defaultConn)
	service := user.NewService(repository)
	controller := user.NewController(service)
	handler := Router(controller)
	server := http.NewServer(option, handler)
	v := gRPCServerOptions()
	userServer := user.NewServer(service)
	registerServiceFunc := gRPCRegisterServiceFn(userServer)
	grpcServer := grpc.NewServer(v, registerServiceFunc)
	listener := grpc.NewListener(viper)
	appApp := app.NewApp(server, grpcServer, listener)
	return appApp
}

// wire.go:

var ProviderSet = wire.NewSet(
	Router,
	gRPCServerOptions,
	gRPCRegisterServiceFn,
)

var Set = wire.NewSet(config.ProviderSet, app.ProviderSet, db.ProviderSet, user.ProviderSet, http.ProviderSet, grpc.ProviderSet, ProviderSet)
