// Code generated by "stringer -type=BizError -output=iota_stringer.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrMarshalFailed-1000001]
	_ = x[ErrUnmarshalFailed-1000002]
	_ = x[ErrUserNotFound-1050003]
	_ = x[ErrUserUpdateNameFailed-1050004]
	_ = x[Err更新用户手机号码失败-1050005]
}

const (
	_BizError_name_0 = "ErrMarshalFailedErrUnmarshalFailed"
	_BizError_name_1 = "ErrUserNotFoundErrUserUpdateNameFailedErr更新用户手机号码失败"
)

var (
	_BizError_index_0 = [...]uint8{0, 16, 34}
	_BizError_index_1 = [...]uint8{0, 15, 38, 71}
)

func (i BizError) String() string {
	switch {
	case 1000001 <= i && i <= 1000002:
		i -= 1000001
		return _BizError_name_0[_BizError_index_0[i]:_BizError_index_0[i+1]]
	case 1050003 <= i && i <= 1050005:
		i -= 1050003
		return _BizError_name_1[_BizError_index_1[i]:_BizError_index_1[i+1]]
	default:
		return "BizError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
