// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package http

import (
	"github.com/google/wire"
	"github.com/wenzong/demo/biz/user"
	"github.com/wenzong/demo/infra/app"
	"github.com/wenzong/demo/infra/config"
	"github.com/wenzong/demo/infra/db"
	"github.com/wenzong/demo/infra/http"
)

// Injectors from wire.go:

func App() *app.App {
	viper := config.NewConfig()
	option := http.NewOption(viper)
	defaultConn := db.NewDefaultConn(viper)
	secondConn := db.NewSecondConn(viper)
	service := user.NewService(defaultConn, secondConn)
	controller := user.NewController(service)
	handler := Router(controller)
	server := http.NewServer(option, handler)
	appApp := app.NewApp(server)
	return appApp
}

// wire.go:

var Set = wire.NewSet(config.ProviderSet, app.ProviderSet, db.ProviderSet, user.ProviderSet, http.ProviderSet, Router)
